version: '2.3'

services:
  gunicorn:
    build:
      context: .
      target: prod
    environment:
      NEO4J_HOST: '//neo4j'
      NEO4J_PORT: 7687
      NEO4J_AUTH: ''
      NEO4J_PSWD: ''
    ports:
      - "8000:8000"

  neo4j:
    image: neo4j:3.5
    environment:
      NEO4J_AUTH: none
